#Pytorch fundamentals


In [ ]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


##Introduction to tensors




###Creating Tensors

####Scalar

In [ ]:
# Scalar
scalar = torch.tensor(7)        #To convert to Tensor
scalar

tensor(7)

In [ ]:
# To get the dimension of the scalar
scalar.ndim

0

In [ ]:
# To convert from tensor back to Int
scalar.item()

7

####Vector

In [ ]:
#Vector
vector = torch.tensor([7,7])       #To convert TO Tensor
vector

tensor([7, 7])

In [ ]:
vector.ndim         #To get the dimension

1

In [ ]:
vector.shape

torch.Size([2])

####Matrix

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

####TENSOR

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

###RANDOM TENSORS

####RANDOM TENSOR NOT IMAGE

In [ ]:
# Random Tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0431, 0.8806, 0.8775, 0.5000],
        [0.9848, 0.9008, 0.5031, 0.0663],
        [0.9052, 0.2538, 0.4518, 0.8361]])

In [ ]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

####CREATE A RANDOM TENSOR WITH SIMILAR SHAPE TO AN IMAGE

In [ ]:
random_image_size_tensor = torch.rand(256,256,3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([256, 256, 3]), 3)

###Creating Tensors with 0s and 1s in Pytorch

####Creating Zeros

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

####Creating Ones

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensors and tensors-Like

####Creating a tensor range

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

####Creating Tensors like

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Dealing with tensor datatypes

In [ ]:
float_32 = torch.tensor([3,4,5], dtype=None, device=None, requires_grad=False)
float_32

tensor([3, 4, 5])

In [ ]:
float_32.dtype, float_32.type(torch.float32), float_32.dtype

(torch.int64, tensor([3., 4., 5.]), torch.int64)

###Manipulating Tensors


####Addition

In [ ]:
tensor_1 = torch.tensor([1,2,3])
tensor_1, tensor_1 + 10,

(tensor([1, 2, 3]), tensor([11, 12, 13]))

####Substraction

In [ ]:
tensor_2 = torch.tensor([3,2,1])
tensor_2, tensor_2 - 10, tensor_2.shape, tensor_2.ndim


(tensor([3, 2, 1]), tensor([-7, -8, -9]), torch.Size([3]), 1)

####Element wise Multiplication

In [ ]:
tensor_3 = torch.tensor([4,3,5])
tensor_3, tensor_3 * 2, tensor_3 * tensor_3

(tensor([4, 3, 5]), tensor([ 8,  6, 10]), tensor([16,  9, 25]))

####Matrix Multiplication

In [ ]:
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4)

torch.mm(tensor_a, tensor_b.T)

tensor([[1.8378, 1.0008, 1.3993],
        [1.8816, 1.5963, 1.5000],
        [1.6571, 1.6320, 1.3241]])

####Tensor Aggregation

In [ ]:
x = torch.arange(10,100,10)
x, x.min(), x.max(), x.argmin(), x.argmax(), x.sum()

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor(10),
 tensor(90),
 tensor(0),
 tensor(8),
 tensor(450))

###Reshaping, Viewing, Stacking, Squeezing, an Unsqueezing

####RESHAPE

In [ ]:
#Adds and Extra dimension but the number of elements remain 9. Hence the reshape must be compatible with the original size in terms of elements
tensor_c = torch.arange(1, 13)
print(f"this is tensor_c without the reshaping: {tensor_c}")
tensor_c_reshaped = torch.reshape(tensor_c, (2,2,3))
print(f"this is tensor_c with the reshaping: {tensor_c_reshaped}")
tensor_c_reshaped[0][1][2] = 7
tensor_c_reshaped

this is tensor_c without the reshaping: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
this is tensor_c with the reshaping: tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


tensor([[[ 1,  2,  3],
         [ 4,  5,  7]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

####VIEW

In [ ]:
tensor_d = torch.arange(1, 13)
tensor_d_view = tensor_d.view(2,6)
tensor_d_view[0][0] = 120
tensor_d_view, tensor_d

(tensor([[120,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12]]),
 tensor([120,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12]))

####Stacking

In [ ]:
tensor_e = torch.arange(1, 13)

e_stacked = torch.stack((tensor_c_reshaped, tensor_c_reshaped), dim=1)
e_stacked

tensor([[[[ 1,  2,  3],
          [ 4,  5,  7]],

         [[ 1,  2,  3],
          [ 4,  5,  7]]],


        [[[ 7,  8,  9],
          [10, 11, 12]],

         [[ 7,  8,  9],
          [10, 11, 12]]]])

####SQUEEZE and UNSQUEEZE

In [ ]:
#squeeze, removes all 1 dimensions from the shape of a tensor

tensor_f = torch.zeros(2,1,1,1,2,2,1,2)
tensor_f.shape
y = torch.squeeze(tensor_f)
y.shape, tensor_f.shape

(torch.Size([2, 2, 2, 2]), torch.Size([2, 1, 1, 1, 2, 2, 1, 2]))

In [ ]:
#unsqueeze, adds 1 dimension to the shape
z = torch.unsqueeze(y, dim=0)
z.shape

torch.Size([1, 2, 2, 2, 2])

###PERMUTE

In [ ]:
#To rearrange the axis of dimensions
tensor_h = torch.rand(3,4)
tensor_h
torch_perm = torch.permute(tensor_h, (1,0))
torch_perm.shape

torch.Size([4, 3])

###PYTORCH AND NUMPY

In [ ]:
#numpy array to Pytorch: torch.from_numpy(ndarray)
#Pytorch to numpy: torch.tensor.numpy()
import numpy as np
np_array = np.arange(1,8)
np_array, torch.from_numpy(np_array), torch.from_numpy(np_array).numpy()

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7]),
 array([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
#From Tensor to numpy

###SETTING RANDOM SEED

In [ ]:
a = 43
torch.manual_seed(a)

tensor_j = torch.rand(3,2)
tensor_j

tensor([[0.4540, 0.1965],
        [0.9210, 0.3462],
        [0.1481, 0.0858]])

#EXERCISES

####1.  Create a random tensor with shape (7, 7).

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.rand(7,7)
tensor_a

tensor([[0.5909, 0.0659, 0.7476, 0.6253, 0.9392, 0.1338, 0.5191],
        [0.5335, 0.5375, 0.7058, 0.4275, 0.2761, 0.8396, 0.1563],
        [0.1072, 0.7261, 0.3241, 0.8892, 0.1318, 0.8375, 0.5625],
        [0.4138, 0.8621, 0.2793, 0.5834, 0.3287, 0.6773, 0.7046],
        [0.9207, 0.2337, 0.6257, 0.4624, 0.8655, 0.1695, 0.3284],
        [0.8663, 0.6951, 0.3651, 0.6565, 0.6841, 0.3490, 0.0966],
        [0.1141, 0.8013, 0.4495, 0.7612, 0.1200, 0.9413, 0.6572]])

####2.  Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
tensor_b = torch.rand(1,7)
tensor_b

tensor([[0.4698, 0.2889, 0.4140, 0.1500, 0.0763, 0.3132, 0.8006]])

In [ ]:
torch.mm(tensor_a, tensor_b.T)

tensor([[1.2292],
        [1.1714],
        [1.2504],
        [1.4479],
        [1.2106],
        [1.0963],
        [1.4155]])

####3. Set the random seed to 0 and do exercises 2 & 3 over again

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(7,7)
tensor_c


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(1,7)
tensor_d

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [ ]:
torch.mm(tensor_c, tensor_c.T)

tensor([[1.5985, 1.1173, 1.2741, 1.6838, 0.8279, 1.0347, 1.2498],
        [1.1173, 1.7231, 1.4061, 1.9499, 0.9564, 1.3146, 1.1037],
        [1.2741, 1.4061, 2.0522, 1.8029, 1.4137, 1.7786, 1.0244],
        [1.6838, 1.9499, 1.8029, 3.1500, 1.3352, 2.1484, 1.9877],
        [0.8279, 0.9564, 1.4137, 1.3352, 1.2619, 1.3505, 0.7881],
        [1.0347, 1.3146, 1.7786, 2.1484, 1.3505, 2.3192, 1.4202],
        [1.2498, 1.1037, 1.0244, 1.9877, 0.7881, 1.4202, 1.7923]])

####4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
torch.cuda.manual_seed(1234)

####5.  Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
import torch

device = "cuda"
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"
torch.cuda.manual_seed(1234)
tensor_x = torch.rand((2,3), dtype=None, device=device, requires_grad=None)

tensor_x_gpu = tensor_x.to(device)
tensor_x_gpu

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [ ]:
torch.cuda.manual_seed(1234)
tensor_y = torch.rand((2,3), dtype=None, device=device, requires_grad=None)
tensor_y_gpu = tensor_x.to(device)
tensor_y_gpu


tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

####6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
tensor_gpu_mul = torch.mm(tensor_x_gpu, tensor_y_gpu.T)
tensor_gpu_mul

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

####7. Find the maximum and minimum values of the output of 7.

In [ ]:
tensor_gpu_mul.max()

tensor(1.4578, device='cuda:0')

####8. Find the maximum and minimum index values of the output of 7.

In [ ]:
tensor_gpu_mul.argmin(), tensor_gpu_mul.argmax()


(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

####9.  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
torch.cuda.manual_seed(7)
tensor_n = torch.rand((1, 1, 1, 10), dtype=None, device=device, requires_grad=None)
red = tensor_n.squeeze()
tensor_n, tensor_n.shape, red, red.shape

(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))

In [87]:
%cd /content


/content


In [89]:
import shutil
shutil.copy("/content/drive/MyDrive/Colab Notebooks/00_Pytorch_Fundamentals.ipynb", "/content/Pytorch-course-on-UDEMY--Notes-and-Codes")

'/content/Pytorch-course-on-UDEMY--Notes-and-Codes/00_Pytorch_Fundamentals.ipynb'

In [97]:
%cd /content/Pytorch-course-on-UDEMY--Notes-and-Codes


/content/Pytorch-course-on-UDEMY--Notes-and-Codes


In [104]:
!git add 00_Pytorch_Fundamentals.ipynb
!git commit -m "My First Pytorch code"
!git branch -M main

On branch main
nothing to commit, working tree clean


In [105]:
!git branch --unset-upstream

fatal: Branch 'main' has no upstream information


In [103]:
!git push -u origin main

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 7.90 KiB | 7.90 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: 
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote: 
remote:     - Push cannot contain secrets
remote: 
remote:     
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push
remote:     
remote:     
remote:       —— GitHub Personal Access Token ——————————————————————
remote:        locations:
remote:          - commit: 50e946a6a5a4f8c526f6376c74ea6cb6fae7841b
r